language: go
os:
    - linux
    - osx
install:
    - go get -t -d -v ./...
    - git checkout $TRAVIS_BRANCH
    - git branch --set-upstream-to=origin/$TRAVIS_BRANCH
script:
    - go build ./
    - go test -v
