name: CI
on:
  push:
    paths-ignore:
      - README.md
    tags-ignore:
      - '**'
    # This is necessary https://github.community/t/using-on-push-tags-ignore-and-paths-ignore-together/16931
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Build sources
        run: go build
        env:
          # Note: -race requires cgo
          CGO_ENABLED: 0
      - name: Run smoke tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go test -v
  linter:
    name: Run staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Check Go sources are formatted
        run: |
          diffs="$(gofmt -d ./*.go)"
          if [[ "$diffs" != "" ]]; then
            echo "$diffs" >&2
            exit 1
          fi
      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: Run staticcheck
        run: |
          staticcheck --version
          staticcheck ./
  action:
    name: Check action
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip action check]')"
    steps:
      - uses: actions/checkout@v3
      - name: Run action
        uses: ./action/
        with:
          file: CHANGELOG_FROM_ACTION.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false
      - name: Get output from latest stable command
        run: |
          version="$(git tag --list 'v*.*.*' --sort '-v:refname' | head -n 1)"
          version="${version#v}"
          echo "extracted latest version: ${version}"
          curl -LO "https://github.com/rhysd/changelog-from-release/releases/download/v${version}/changelog-from-release_${version}_linux_amd64.tar.gz"
          tar xf "changelog-from-release_${version}_linux_amd64.tar.gz" changelog-from-release
          ./changelog-from-release > CHANGELOG_FROM_COMMAND.md
      - run: diff -u CHANGELOG_FROM_ACTION.md CHANGELOG_FROM_COMMAND.md
