name: CI
on:
  push:
    paths-ignore:
      - README.md
  pull_request:

jobs:
  tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Build sources
        run: |
          go version
          go get -t -d -v ./...
          go build ./
      - name: Run smoke tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go test -v
  linter:
    name: Golint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
      - run: ls -l $GOROOT
      - run: go get golang.org/x/lint/golint
      - name: Add $GOPATH/bin to $PATH
        run: echo "::add-path::$(go env GOPATH)/bin"
      - run: golint -set_exit_status
  action:
    name: Check action
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip action check]')"
    steps:
      - uses: actions/checkout@v2
      - name: Run action
        uses: ./action/
        with:
          file: CHANGELOG2.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: false
      - run: diff CHANGELOG.md CHANGELOG2.md
