name: Private Repository
on:
  push:
    branches: [master]
env:
  CGO_ENABLED: 0

jobs:
  private-repo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'
      - run: go build
      - name: Generate
        run: |
          ./changelog-from-release -r 'https://github.com/rhysd/private-repo-test' > OUTPUT.md
          cat OUTPUT.md
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Check
        run: |
          CHANGELOG="$(cat OUTPUT.md)"
          if [[ "$CHANGELOG" != *"# [v0.0.0](https://github.com/rhysd/private-repo-test/releases/tag/v0.0.0) - 16 Jan 2023"* ]]; then
            echo 'Unexpected changelog output:' 1>&2
            cat OUTPUT.md 1>&2
            exit 1
          fi
